회원가입 기능 구현 완료, UI 기능 구현 완료
MentalJava/getx-login pull request #4
Opened 2024-07-01 15:20 UTC by MentalJava

회원가입 기능 구현 완료

Obx로 로딩 인디케이터 구현 완료

suffixicon obscuretext 비밀번호 가리기 버튼 활성화 완료 (Obx로 관리)

vaildator if 구문으로 유효성 검사 완료

2024-07-03 00:29 UTC, kdjun97 approved these changes
전반적으로 좋습니다.
아직은 View, ViewModel 을 나누는 것은 생각하지 않도록 할게요. 
GetX의 특성상, GetXController에서 즉 business logic을 처리하는 단에서 UI에 접근해도 괜찮지만, 원래는 이렇게 하지 않아요. 

지금은 기능 구현에 집중을 해봅시다. 다만, 추후에는 점점 앱 개발 규칙을 따르도록 갈거예요.

SignUp, SignIn, Home화면까지 잘 봤습니다. 고생하셨습니다~ 👍  @MentalJava

2024-07-03 00:29 UTC, kdjun97 commented on android/app/google-services.json
> -      "oauth_client": [],
google-services.json 내부에 key 값이 들어가있어요.
해당 key들은 유출되어 다른사람이 사용할 수 없도록 처리가 필요할 것 같아요. @MentalJava

2024-07-03 00:29 UTC, kdjun97 commented on lib/src/controllers/auth_controller.dart
> +
Future가 빠진 것 같습니다. @MentalJava

2024-07-03 00:29 UTC, kdjun97 commented on android/app/src/main/AndroidManifest.xml
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android">
앱에서 인터넷을 가거나 하면 아래처럼 permission이 필요해요~ good @MentalJava

2024-07-03 00:29 UTC, kdjun97 commented on lib/src/controllers/auth_controller.dart
> +  static AuthController instance = Get.find();
안쓸거면 주석 제거. 제가 알기로 Rx는 안쓰는기로 한걸로 알아여~ @MentalJava

2024-07-03 00:29 UTC, kdjun97 commented on lib/src/pages/login.dart
> -              width: double.infinity,
수정 반영 good @MentalJava

2024-07-03 00:29 UTC, kdjun97 commented on lib/src/pages/sign_up.dart
> +                              if (value == null || value.isEmpty) {
여러가지 케이스에 대해 validation 처리 좋아요. @MentalJava

2024-07-03 19:07 UTC, MentalJava commented on android/app/google-services.json
> -      "oauth_client": [],
확인해보겠습니다 감사합니다 ! @kdjun97

2024-07-03 19:08 UTC, MentalJava commented on lib/src/controllers/auth_controller.dart
> +
다시 수정 완료했습니다 😊 @kdjun97

2024-07-03 19:09 UTC, MentalJava commented on android/app/src/main/AndroidManifest.xml
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android">
헤매면서 permission이 꼭 필요하다는 걸 알았습니다 ! 꼭 기억해두겠습니다 ✌ @kdjun97

2024-07-03 19:09 UTC, MentalJava commented on lib/src/controllers/auth_controller.dart
> +  static AuthController instance = Get.find();
바로 수정 완료했습니다 ! @kdjun97

2024-07-03 19:10 UTC, MentalJava commented on lib/src/pages/login.dart
> -              width: double.infinity,
✌✌ @kdjun97

2024-07-03 19:10 UTC, MentalJava commented on lib/src/pages/sign_up.dart
> +                              if (value == null || value.isEmpty) {
감사합니다 ! 더 좋은 방법이 있는지 계속 연구해보겠습니다 👏 @kdjun97

2024-07-04 04:20 UTC, kdjun97 requested changes
쓸데없는 파일들이 같이 올라온 것 같은데,
.gitignore 설정 다시 할 필요 있고,
코멘트 위주로 수정 해주세요. @MentalJava

2024-07-04 04:20 UTC, kdjun97 commented on android/app/google-services.json
> -          "client_id": "125607892840-6go361rj0ktgou2kdoabnbncgb12n88e.apps.googleusercontent.com",
google-service.json 파일은 .gitignore로 설정해서 안올리는게 좋습니다.
수정 반영 부탁드립니다.
@MentalJava

2024-07-04 04:20 UTC, kdjun97 commented on lib/src/app.dart
>            name: "/",
const를 뺀 이유? @MentalJava

2024-07-04 04:20 UTC, kdjun97 commented on lib/src/controllers/auth_controller.dart
> +  static AuthController instance = Get.find();
수정 완료된 건은 아래 Resolve conversation 버튼으로 해결했다고 표시해주세요~ @MentalJava

2024-07-04 04:20 UTC, kdjun97 commented on lib/src/controllers/auth_controller.dart
> +
이런식의 함수명 너무 좋습니다. 
간혹 줄이는거나 의미 없는 함수명 ex) temp() 이런것들 쓰는 경우가 많은데,
길더라도 이렇게 써주면 좋을 것 같아요. 좋습니다. 👍  @MentalJava

2024-07-04 04:20 UTC, kdjun97 commented on lib/src/controllers/google_controller.dart
> +
camelCase -> loginWithGoogle @MentalJava

2024-07-04 04:20 UTC, kdjun97 commented on linux/flutter/generated_plugins.cmake
>  list(APPEND FLUTTER_PLUGIN_LIST
cmake gitignore 처리. @MentalJava

2024-07-04 04:20 UTC, kdjun97 commented on linux/flutter/generated_plugin_registrant.cc
이런것도 .gitignore 처리 @MentalJava

2024-07-05 07:31 UTC, MentalJava commented on lib/src/app.dart
>            name: "/",
확인해서 수정했습니다 ! @kdjun97

2024-07-05 07:31 UTC, MentalJava commented on android/app/google-services.json
> -          "client_id": "125607892840-6go361rj0ktgou2kdoabnbncgb12n88e.apps.googleusercontent.com",
확인했습니다. @kdjun97

2024-07-05 07:32 UTC, MentalJava commented on lib/src/controllers/google_controller.dart
> +
바로 수정 완료했습니다 ! @kdjun97

2024-07-05 07:36 UTC, MentalJava commented on linux/flutter/generated_plugin_registrant.cc
네 알겠습니다 😀 @kdjun97

2024-07-05 07:38 UTC, MentalJava commented on lib/src/controllers/auth_controller.dart
> +
제가 헷갈리는 부분도 많아서 확실히 어떤 기능을 하는 함수인지 적어놓는게 보기편해서 디테일하게 적어봤습니다 ! 
칭찬 감사합니다 ! @kdjun97

2024-07-05 07:38 UTC, MentalJava commented on linux/flutter/generated_plugins.cmake
>  list(APPEND FLUTTER_PLUGIN_LIST
네 확인했습니다 ! @kdjun97

2024-07-05 08:39 UTC, MentalJava commented
.gitignore 는 다음 프로젝트때부터 꼭 적용해서 필요한 파일들만 올리도록 하겠습니다 ! @kdjun97

2024-07-05 08:49 UTC, kdjun97 commented
> .gitignore 는 다음 프로젝트때부터 꼭 적용해서 필요한 파일들만 올리도록 하겠습니다 ! @kdjun97

확인이요. 해당 PR 닫을게요. @MentalJava

2024-07-05 08:50 UTC, kdjun97 approved these changes

2024-07-05 08:50 UTC, merged